create `judge stability odd`
chatblanc-ciel/filter_param pull request #29
Opened 2021-08-11 12:28 UTC by 9071-dynamix

極係数による安定性判別(安定性条件から外れたときのペナルティ計算)

2021-08-12 00:28 UTC, chatblanc-ciel requested changes

2021-08-12 00:28 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +double FilterParam::judge_stability_odd(const vector<double>& coef)
`double FilterParam::judge_stability_odd(const vector<double>& coef) const`にしてほしい

2021-08-12 00:28 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	}
k→mに変えてほしい

2021-08-12 00:28 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	}
インデントの修正
if()
{
      penalty・・・
}
みたいにタブで変更する

2021-08-12 11:10 UTC, chatblanc-ciel requested changes

2021-08-13 06:50 UTC, chatblanc-ciel requested changes

2021-08-13 06:50 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +    	penalty += coef.at(m) * coef.at(m) + coef.at(m + 1) * coef.at(m + 1);
インデント合わせてー

2021-08-13 06:50 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +    	penalty += coef.at(n_order + 1) * coef.at(n_order + 1);
これも

2021-08-13 06:55 UTC, chatblanc-ciel requested changes
`freq_res`と同じように
https://github.com/chatblanc-ciel/filter_param/blob/83ca821cc6b8b2d66dc14e1929beb24a3e9896ab/lib/filter_param.cpp#L166
`judge_stability`で使えるようにしてほしい

2021-08-13 10:49 UTC, chatblanc-ciel requested changes

2021-08-13 10:49 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +			stability_func = bind(&FilterParam::judge_stability_odd, this,placeholders::_1);
分母が奇数次になる場合は一か所だけ？

2021-08-13 10:49 UTC, chatblanc-ciel commented on lib/filter_param.hpp
> +	double judge_stability_odd(const vector<double>& coef) const;
ここ消えてないような？

2021-08-13 10:49 UTC, chatblanc-ciel commented on main.cpp
> +	};
@name1204 のコードと同じように

1. 安定性を満たす場合
2. b1が違反
3. |b2|が違反
4. b1 & b2 の条件が違反

の条件でそれぞれ、期待通りの動作か確認する必要があります

2021-08-14 02:20 UTC, 9071-dynamix commented on lib/filter_param.hpp
> +	double judge_stability_odd(const vector<double>& coef) const;
すみません、全く覚えてないのですが179行目は消すように、というようなことを言っていたのでしょうか

2021-08-16 07:26 UTC, chatblanc-ciel requested changes

2021-08-16 07:26 UTC, chatblanc-ciel commented on main.cpp
> +void test_FilterParam_judge_stability_odd();
ここの順番

2021-08-16 07:37 UTC, chatblanc-ciel approved these changes

2021-08-16 07:37 UTC, merged