create 'Amplitude_Chara'
chatblanc-ciel/filter_param pull request #49
Opened 2021-10-02 06:48 UTC by 9071-dynamix

振幅特性図の描画の作成

2021-10-02 06:52 UTC, chatblanc-ciel requested changes

2021-10-02 06:52 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +void FilterParam::gprint_amp(const vector<double> &coef) const
- [ ] 出力のファイル名も引数に取ろう
- [ ] 描画範囲の指定
- [ ] 関数の仕様を明記

2021-10-02 06:52 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +    fprintf(gp, "plot '-' with lines title \"\n");
フォーマット整えてほしい
インデントズレてて気持ち悪い

2021-10-02 06:52 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +			fprintf(gp,"%lf %f\n", i*(M_PI/250), log10(abs(res)));
amplitudeは対数とらなくない？

2021-10-02 06:52 UTC, chatblanc-ciel commented on main.cpp
> +void test_FilterParam_amplitude()
テストの説明いれる

2021-10-02 08:10 UTC, 9071-dynamix commented on lib/filter_param.cpp
> +    fprintf(gp, "plot '-' with lines title \"\n");
これに関しては多分github上でずれて表示されているだけで実際には揃っていると思います。
流石にずれていたら気持ち悪く感じるので自分でも絶対に整えるはずです。

2021-10-07 10:06 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> + * double right : 帯域の右端正規化周波数 (0:0.5]
これ検査あるの？

2021-10-07 10:08 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	vector<BandParam> range{FilterParam::gen_bands(FilterType::LPF, left, right)};
惜しいけど、`FilterParam::gen_bands`をここで使ってほしくないのよ

2021-10-07 10:34 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +		}
```suggestion
		for(unsigned int i = 0 ; i < band_res.size() ; ++i)
		{
			if(left*2*M_PI <= i*(M_PI/250) && i*(M_PI/250) <= right*2*M_PI)
			{
				printf("%lf %f\n", i*(M_PI/250), abs(res));
				fprintf(gp,"%lf %f\n", i*(M_PI/250), abs(res));
			}
		}
```
インデックス使いたいなら、インデックスで回そう
あと条件判定は関数冒頭で1回だけ行う

2021-10-07 16:14 UTC, chatblanc-ciel requested changes
test

2021-10-07 16:16 UTC, chatblanc-ciel requested changes
test

2021-10-07 17:16 UTC, chatblanc-ciel requested changes
test

2021-10-10 20:35 UTC, chatblanc-ciel requested changes

2021-10-10 20:35 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	auto freq_res = fparam.freq_res(coef);
空行潰していいよ

2021-10-10 20:35 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +			fprintf(gp,"%lf %f\n", i*(((right-left)*2*M_PI)/250), abs(band_res.at(i)));
たぶん、まだこれではダメな気がするけど…
あと固定値は事前計算で

2021-10-11 13:10 UTC, chatblanc-ciel requested changes

2021-10-11 13:10 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	double grange = (right-left)*2*M_PI/250; //固定値の事前計算
```suggestion
	constexpr double grange = (right-left)*2.0*M_PI/250.0; //固定値の事前計算
```
left, rightは入れれないかもしれません。
コンパイル時定数にならないかもなので

`constexpr`を使わない場合、計算できる部分は事前に処理するべきです
2.0*PI/250 ---> PI / 125

2021-10-11 13:10 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	fprintf(gp, "set output 'Amplitude.png'\n");
filename入ってないけど

2021-10-11 13:10 UTC, chatblanc-ciel commented on main.cpp
> +void test_FilterParam_magnitude();
```suggestion
void test_FilterParam_gprint_amp();
void test_FilterParam_gprint_mag();
```

2021-10-11 13:10 UTC, chatblanc-ciel commented on main.cpp
> +	string filename("Mag1");
拡張子ない

2021-10-11 13:10 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> + * string &filename : 出力するファイル名
拡張子に関する補足

2021-10-11 13:10 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +FilterParam::FilterParam
ドキュメントほしい

2021-10-30 06:44 UTC, chatblanc-ciel requested changes

2021-10-30 06:44 UTC, chatblanc-ciel commented on main.cpp
> +	/* BandParamより共に範囲内・left<rightのため成功 */
```suggestion
	// BandParamが共に[0.0 : 0.5]の範囲内＆``left < right``のため成功
```
1行コメントなので

2021-10-30 06:44 UTC, chatblanc-ciel commented on main.cpp
> +	*/
```suggestion
	// 以下失敗例
	// Fparam.gprint_amp(coef_test, string("Amp5.png"), -0.2, 0.3); //BandParamよりleft<0.0のため失敗

	// Fparam.gprint_amp(coef_test, string("Amp6.png"), 0.3, 0.2); //BandParamよりleft>rightのため失敗

	// Fparam.gprint_amp(coef_test, string("Amp7.png"), 0.2, 0.6); //BandParamよりright>0.5のため失敗
	
```

2021-10-30 06:59 UTC, chatblanc-ciel approved these changes

2021-10-30 06:59 UTC, merged